# Variable to change cluster-agent name in deployment
nameOverride:

# Cluster agent deployment mode (PRIMARY | NAMESPACED)
deploymentMode: PRIMARY

installClusterAgent: true
installInfraViz: false

# Docker images
imageInfo:
  agentImage: docker.io/appdynamics/cluster-agent
  agentTag: 21.12.0
  operatorImage: docker.io/appdynamics/cluster-agent-operator
  operatorTag: 21.12.0
  imagePullPolicy: Always                               # Will be used for operator pod
  machineAgentImage: docker.io/appdynamics/machine-agent-analytics
  machineAgentTag: 21.9.0
  machineAgentWinTag: 21.9.0-win-ltsc2019
  netVizImage: docker.io/appdynamics/machine-agent-netviz
  netvizTag: 21.3.0

# AppDynamics controller info (null VALUES TO BE PROVIDED BY THE USER)
controllerInfo:
  url: null
  account: null
  username: null
  password: null
  accessKey: null
  globalAccount: null
  
  # SSL properties
  customSSLCert: null
  
  # Proxy config
  authenticateProxy: false
  proxyUrl: null
  proxyUser: null
  proxyPassword: null 

# RBAC config
createServiceAccount: true
agentServiceAccount: appdynamics-cluster-agent
operatorServiceAccount: appdynamics-operator
infravizServiceAccount: appdynamics-infraviz

# Cluster agent config
clusterAgent:
  nsToMonitor:
    - default
  clusterMetricsSyncInterval: 60
  metadataSyncInterval: 60
  eventUploadInterval: 10
  httpClientTimeout: 30
  podBatchSize: 6
  imagePullSecret: ""
  containerProperties:
    containerBatchSize: 5
    containerParallelRequestLimit: 1
    containerRegistrationInterval: 120
  logProperties:
    logFileSizeMb: 5
    logFileBackups: 3
    logLevel: INFO
  metricProperties:
    metricsSyncInterval: 30
    metricUploadRetryCount: 2
    metricUploadRetryIntervalMilliSeconds: 5

# Pod filter config
podFilter: {}

# Instrumentation config
instrumentationConfig:
  enabled: false

# InfraViz config
infraViz:
  nodeOS: "linux"
  enableMasters: false
  stdoutLogging: false
  enableContainerHostId: false
  enableServerViz: false
  enableDockerViz: false

# Netviz config
netViz:
  enabled: false
  netVizPort: 3892

# Agent pod specific properties
agentPod:
  nodeSelector: {}
  tolerations: []
  resources:
    limits:
      cpu: "1250m"
      memory: "300Mi"
    requests:
      cpu: "750m"
      memory: "150Mi"
  labels: {}

# Operator pod specific properties
operatorPod:
  nodeSelector: {}
  tolerations: []
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

# Infraviz pod specific properties
infravizPod:
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    limits:
      cpu: 500m
      memory: "1G"
    requests:
      cpu: 200m
      memory: "800M"
  # overrideVolumeMounts property is valid only after 0.6.10 operator version
  overrideVolumeMounts:

# Subcharts boolean install switches
install:
  metrics-server: false
